# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_encodedataset_extra_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodedataset',
            name='antibody',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='encodedataset',
            name='cell_type',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='encodedataset',
            name='data_type',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='encodedataset',
            name='localization',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='encodedataset',
            name='phase',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='encodedataset',
            name='rna_extract',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='encodedataset',
            name='treatment',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
