# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20160203_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurelist',
            name='text',
        ),
        migrations.AddField(
            model_name='featurelist',
            name='dataset',
            field=models.FileField(blank=True, max_length=256, upload_to=''),
        ),
    ]
