# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_auto_20160211_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcorrelationmatrix',
            name='matrix',
            field=models.FileField(max_length=256, upload_to='dcm/'),
        ),
        migrations.AlterField(
            model_name='featurelistcountmatrix',
            name='matrix',
            field=models.FileField(max_length=256, upload_to='fcm/'),
        ),
    ]
