# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 17:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_auto_20160216_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='output',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='datasetcorrelationmatrix',
            name='analysis',
        ),
        migrations.DeleteModel(
            name='DatasetCorrelationMatrix',
        ),
    ]
