# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0016_auto_20160218_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='output',
        ),
    ]
