# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_remove_analysis_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='output',
            field=models.FileField(max_length=256, blank=True, null=True, upload_to='analysis/'),
        ),
    ]
