# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_analysis_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='sort_vector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.SortVector'),
        ),
    ]
