# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_auto_20160414_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortvector',
            name='text',
        ),
        migrations.AddField(
            model_name='sortvector',
            name='vector',
            field=models.FileField(default=-1, max_length=256, upload_to=''),
            preserve_default=False,
        ),
    ]
