# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_datasetdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdownload',
            name='filesize',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='datasetdownload',
            name='md5',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
