# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_auto_20160422_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdataset',
            name='data_ambiguous',
        ),
        migrations.RemoveField(
            model_name='userdataset',
            name='data_minus',
        ),
        migrations.RemoveField(
            model_name='userdataset',
            name='data_plus',
        ),
        migrations.AddField(
            model_name='userdataset',
            name='ambiguous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambiguous', to='analysis.DatasetDownload'),
        ),
        migrations.AddField(
            model_name='userdataset',
            name='minus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minus', to='analysis.DatasetDownload'),
        ),
        migrations.AddField(
            model_name='userdataset',
            name='plus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plus', to='analysis.DatasetDownload'),
        ),
    ]
