# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_userdataset_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='featurelist',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='genomicdataset',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sortvector',
            name='validation_notes',
            field=models.TextField(blank=True),
        ),
    ]
