# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_auto_20160504_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurelist',
            name='dataset',
            field=models.FileField(max_length=256, upload_to=''),
        ),
    ]
